# Generated by Django 6.0.2 on 2026-04-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_actividad_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivoespecifico',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
