# Generated by Django 6.0.2 on 2026-03-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_descripcion_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField(choices=[(1, 'Ene'), (2, 'Feb'), (3, 'Mar'), (4, 'Abr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Ago'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dic')])),
                ('avance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='proyectos.resultado')),
            ],
            options={
                'unique_together': {('resultado', 'anio', 'mes')},
            },
        ),
    ]
