# Generated by Django 6.0.2 on 2026-03-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_seguimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguimiento',
        ),
    ]
