# Generated by Django 6.0.2 on 2026-05-01 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_remove_proyecto_presupuesto_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Unidad responsable',
                'verbose_name_plural': 'Unidades responsables',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='plandegasto',
            options={'ordering': ['-anio', 'actividad_id']},
        ),
        migrations.AddField(
            model_name='plandegasto',
            name='unidad_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_gasto', to='proyectos.unidad'),
        ),
        migrations.AddConstraint(
            model_name='plandegasto',
            constraint=models.UniqueConstraint(fields=('actividad', 'gasto_elegible', 'anio'), name='uniq_plan_actividad_gasto_anio'),
        ),
    ]
