# Generated by Django 6.0.2 on 2026-05-18 13:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_proyecto_options_remove_proyecto_cumplimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('HONORARIO', 'Honorario'), ('VIATICO', 'Viático')], max_length=15)),
                ('subtipo_compra', models.CharField(blank=True, choices=[('BIENES_INSUMOS', 'Bienes/Insumos'), ('ALIMENTACION', 'Alimentación'), ('ARRIENDO_VEHICULO', 'Arriendo Vehículo'), ('ALOJAMIENTO', 'Alojamiento'), ('PASAJE_AEREO_NACIONAL', 'Pasaje aéreo nacional'), ('PASAJE_AEREO_INTERNACIONAL', 'Pasaje aéreo internacional')], max_length=30)),
                ('centro_responsabilidad', models.CharField(blank=True, max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('valor_sin_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('eliminado', models.BooleanField(db_index=True, default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='proyectos.gasto')),
                ('gasto_elegible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='proyectos.gastoelegible')),
                ('plan_de_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egresos', to='proyectos.plandegasto')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='proyectos.proyecto')),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
