# Generated by Django 6.0.2 on 2026-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_egreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='estado',
            field=models.CharField(choices=[('COMPROMETIDO', 'Comprometido'), ('EJECUTADO', 'Ejecutado')], default='COMPROMETIDO', max_length=15),
        ),
    ]
