# Generated by Django 6.0.2 on 2026-05-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_egreso_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='apellido_persona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='egreso',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='egreso',
            name='cuotas_pagadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='egreso',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='egreso',
            name='impuestos_pagados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='egreso',
            name='meses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='egreso',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='egreso',
            name='nombre_persona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='egreso',
            name='profesion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
