# Generated by Django 6.0.2 on 2026-06-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_egreso_apellido_persona_egreso_cuota_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código de proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
