# Generated by Django 6.0.2 on 2026-08-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_proyecto_codigo_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterModelOptions(
            name='objetivoespecifico',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterModelOptions(
            name='resultado',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='objetivoespecifico',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='resultado',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='orden',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='objetivoespecifico',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
