# Generated by Django 6.0.2 on 2026-08-17 22:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_cuotas_de_honorario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('numero_anio', models.PositiveSmallIntegerField(help_text='1 para el primer año, 2 para el segundo, etc.', verbose_name='Año del proyecto')),
                ('anio_calendario', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año calendario')),
                ('presupuesto_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('presupuesto_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_anuales', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto anual',
                'verbose_name_plural': 'Presupuestos anuales',
                'ordering': ['proyecto_id', 'numero_anio'],
                'constraints': [models.UniqueConstraint(fields=('proyecto', 'numero_anio'), name='uniq_presupuesto_proyecto_numero_anio'), models.UniqueConstraint(fields=('proyecto', 'anio_calendario'), name='uniq_presupuesto_proyecto_anio_calendario')],
            },
        ),
    ]
