# Generated by Django 6.0.2 on 2026-08-18 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_repartir_presupuesto_existente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_limite_original',
            field=models.DateField(blank=True, help_text='La primera que se fijó. No se modifica al reprogramar.', null=True, verbose_name='Fecha límite comprometida'),
        ),
        migrations.CreateModel(
            name='ReprogramacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateField(blank=True, null=True)),
                ('fecha_nueva', models.DateField()),
                ('motivo', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones', to='proyectos.actividad')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reprogramación de actividad',
                'verbose_name_plural': 'Reprogramaciones de actividades',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['actividad', 'creado_en'], name='proyectos_r_activid_bcfc1e_idx')],
            },
        ),
    ]
