# Generated by Django 6.0.2 on 2026-08-18 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_fijar_compromiso_original'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoObjetivoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('presupuesto_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('presupuesto_capital', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_objetivo', to='proyectos.presupuestoanual')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_anuales', to='proyectos.objetivoespecifico')),
            ],
            options={
                'verbose_name': 'Presupuesto anual del objetivo',
                'verbose_name_plural': 'Presupuestos anuales de objetivos',
                'ordering': ['anio__numero_anio'],
                'constraints': [models.UniqueConstraint(fields=('objetivo', 'anio'), name='uniq_presupuesto_objetivo_anio')],
            },
        ),
    ]
