# Generated by Django 6.0.2 on 2026-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0028_plan_de_gasto_por_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Cuándo parte la actividad. Déjala vacía si aún no se define.', null=True, verbose_name='Fecha de inicio'),
        ),
    ]
