# Generated by Django 6.0.2 on 2026-08-19 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0029_actividad_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='anio_inicial',
            field=models.PositiveIntegerField(blank=True, help_text='El año calendario en que empieza a ejecutarse.', null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año 1 del presupuesto'),
        ),
    ]
