# Generated by Django 6.0.2 on 2026-08-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0030_proyecto_anio_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='alcanzado',
            field=models.PositiveIntegerField(default=0, verbose_name='Alcanzado a la fecha'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='meta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Meta comprometida'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='metodo_avance',
            field=models.CharField(blank=True, choices=[('META', 'Meta contable'), ('TRAMOS', 'Escala de tramos'), ('ACTIVIDADES', 'Promedio de sus actividades')], default='', help_text='Vacío: todavía no se define y se calcula desde las actividades.', max_length=12, verbose_name='Cómo se mide el avance'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='tramo',
            field=models.PositiveSmallIntegerField(choices=[(0, '0% — No iniciado'), (25, '25% — Diseñado o planificado'), (50, '50% — En ejecución, primera mitad'), (75, '75% — En ejecución, por cerrar'), (100, '100% — Terminado y verificado')], default=0, verbose_name='Tramo de avance'),
        ),
        migrations.AddField(
            model_name='resultado',
            name='unidad_meta',
            field=models.CharField(blank=True, default='', help_text='Qué se cuenta: convenios, talleres, informes…', max_length=60, verbose_name='Unidad de la meta'),
        ),
    ]
