# Generated by Django 6.0.2 on 2026-06-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0003_backfill_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinforme',
            name='tipo',
            field=models.CharField(choices=[('CREACION', 'Creación'), ('EDICION', 'Edición'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('APROBACION', 'Aprobación'), ('RECHAZO', 'Devolución')], max_length=20),
        ),
    ]
