# Generated by Django 6.0.2 on 2026-06-02 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0005_grupo_encargado_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinforme',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='informes/revisiones/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
