# Generated by Django 6.0.2 on 2026-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NivelRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(db_index=True, max_length=200, verbose_name='ruta del cargo')),
                ('clave', models.CharField(max_length=20, verbose_name='ítem del perfil')),
                ('nivel', models.PositiveSmallIntegerField(default=3, verbose_name='nivel requerido')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='última modificación')),
            ],
            options={
                'verbose_name': 'nivel requerido',
                'verbose_name_plural': 'niveles requeridos',
                'ordering': ['ruta', 'clave'],
                'constraints': [models.UniqueConstraint(fields=('ruta', 'clave'), name='evaluaciones_nivel_unico')],
            },
        ),
    ]
