# Generated by Django 6.0.2 on 2026-04-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_objetivoespecifico_presupuesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivoespecifico',
            old_name='presupuesto',
            new_name='presupuesto_capital',
        ),
        migrations.AddField(
            model_name='objetivoespecifico',
            name='presupuesto_corriente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('PACE', 'Pace'), ('FORT', 'Fortalecimiento'), ('REG', 'Regionales'), ('ADAIN', 'Adain'), ('GORE', 'Gore'), ('RED', 'RED')], default='PACE', max_length=10),
        ),
    ]
