# Generated by Django 6.0.2 on 2026-04-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_rename_presupuesto_objetivoespecifico_presupuesto_capital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='presupuesto_disponible',
        ),
    ]
