# Generated by Django 6.0.2 on 2026-05-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_rename_ejecutado_to_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
