# Generated by Django 6.0.2 on 2026-02-23 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('unidad', models.CharField(max_length=255)),
                ('funcion_institucional', models.CharField(choices=[('DOCENCIA', 'Docencia'), ('INVESTIGACION', 'Investigación'), ('VINCULACION', 'Vinculación con el Medio'), ('GESTION', 'Gestión Estratégica')], max_length=30)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('REVISION_OCT', 'Revisión OCT'), ('DEVUELTA', 'Devuelta con observaciones'), ('APROBADA', 'Aprobada por OCT'), ('POSTULADA', 'Postulada'), ('ADJUDICADA', 'Adjudicada'), ('NO_ADJUDICADA', 'No adjudicada')], default='BORRADOR', max_length=30)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('descarga_horas', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciativas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoIniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='iniciativas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('iniciativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='oct.iniciativa')),
            ],
        ),
    ]
