# Generated by Django 6.0.2 on 2026-02-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
