# Generated by Django 6.0.2 on 2026-03-12 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct', '0002_iniciativa_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fondo', models.CharField(max_length=200)),
                ('link_convocatoria', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('iniciativa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulacion', to='oct.iniciativa')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoFormulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='formulaciones/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('formulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='oct.formulacion')),
            ],
        ),
    ]
