# Generated by Django 6.0.2 on 2026-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct', '0003_formulacion_documentoformulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacion',
            name='estado',
            field=models.CharField(choices=[('BOR', 'Borrador'), ('ENV', 'Enviada a revisión'), ('DEV', 'Devuelta con observaciones'), ('APR', 'Aprobada')], default='BOR', max_length=3),
        ),
        migrations.AddField(
            model_name='formulacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
