# Generated by Django 6.0.2 on 2026-06-10 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct', '0004_formulacion_estado_formulacion_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoIniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREACION', 'Creación'), ('ENVIO', 'Envío a revisión'), ('APROBACION', 'Aprobación'), ('DEVOLUCION', 'Devolución'), ('EDICION', 'Edición'), ('FORMULACION', 'Formulación'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('DOCUMENTO', 'Documento')], max_length=20)),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('iniciativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='oct.iniciativa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_iniciativa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
