# Generated by Django 6.0.2 on 2026-08-12 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oct', '0005_movimientoiniciativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAmbito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(default=2026, verbose_name='Año')),
                ('ambito', models.CharField(choices=[('PROYECTOS', 'Proyectos'), ('LICITACIONES', 'Licitaciones'), ('CONVENIOS', 'Convenios'), ('DONACIONES', 'Donaciones')], max_length=20, verbose_name='Ámbito')),
                ('meta_gestiones', models.PositiveIntegerField(default=0, verbose_name='Meta anual de gestiones')),
            ],
            options={
                'verbose_name': 'meta anual',
                'verbose_name_plural': 'metas anuales',
                'ordering': ['anio', 'ambito'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'ambito'), name='oct_meta_unica')],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(default=2026, verbose_name='Año')),
                ('ambito', models.CharField(choices=[('PROYECTOS', 'Proyectos'), ('LICITACIONES', 'Licitaciones'), ('CONVENIOS', 'Convenios'), ('DONACIONES', 'Donaciones')], max_length=20, verbose_name='Ámbito')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'proyección mensual',
                'verbose_name_plural': 'proyección financiera',
                'ordering': ['anio', 'ambito', 'mes'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'ambito', 'mes'), name='oct_proyeccion_unica')],
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(db_index=True, default=2026, verbose_name='Año')),
                ('codigo', models.CharField(blank=True, max_length=100, verbose_name='Código')),
                ('ambito', models.CharField(choices=[('PROYECTOS', 'Proyectos'), ('LICITACIONES', 'Licitaciones'), ('CONVENIOS', 'Convenios'), ('DONACIONES', 'Donaciones')], max_length=20, verbose_name='Ámbito')),
                ('tipo', models.CharField(blank=True, max_length=200, verbose_name='Tipo de iniciativa')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre de la iniciativa')),
                ('institucion', models.CharField(blank=True, max_length=200, verbose_name='Institución')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('monto_postulado', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Monto postulado')),
                ('estado', models.CharField(choices=[('EN_IDENTIFICACION', 'En identificación'), ('EN_PREPARACION', 'En preparación'), ('PRESENTADA', 'Presentada'), ('EN_EVALUACION', 'En evaluación'), ('ADJUDICADA', 'Adjudicada'), ('NO_ADJUDICADA', 'No adjudicada'), ('DESISTIDA', 'Desistida'), ('SUSCRITA', 'Suscrita'), ('RECIBIDA', 'Recibida')], default='EN_IDENTIFICACION', max_length=20)),
                ('fecha_resultado', models.DateField(blank=True, null=True, verbose_name='Fecha de resultado')),
                ('monto_adjudicado', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Monto adjudicado')),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('origen', models.CharField(choices=[('IMPORTADO', 'Importado del Excel'), ('MANUAL', 'Cargado en el sistema')], default='MANUAL', max_length=10)),
                ('campos_editados', models.JSONField(blank=True, default=list)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestiones_oct_editadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'gestión del tablero',
                'verbose_name_plural': 'gestiones del tablero',
                'ordering': ['ambito', '-fecha_ingreso', 'nombre'],
                'indexes': [models.Index(fields=['anio', 'ambito'], name='oct_gestion_anio_92a14c_idx')],
            },
        ),
    ]
