# Generated by Django 6.0.2 on 2026-03-12 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='aplica_linea_base',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='programa',
        ),
        migrations.AddField(
            model_name='estrategia',
            name='plazo',
            field=models.CharField(choices=[('CORTO', 'Corto plazo'), ('MEDIANO', 'Mediano plazo'), ('LARGO', 'Largo plazo')], default='CORTO', max_length=10),
        ),
        migrations.AddField(
            model_name='indicador',
            name='formula',
            field=models.TextField(blank=True, help_text='Ej: (Cantidad lograda / Meta) * 100'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='linea_base',
            field=models.BooleanField(default=False, verbose_name='¿Aplica línea base?'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='unidad_medida',
            field=models.CharField(choices=[('CAR', 'Caracteres'), ('POR', 'Porcentual'), ('UNI', 'Unitario')], default='UNI', max_length=3),
        ),
        migrations.AddField(
            model_name='programa',
            name='objetivos',
            field=models.ManyToManyField(blank=True, related_name='programas_asociados', to='planificacion.objetivo'),
        ),
        migrations.AddField(
            model_name='programa',
            name='tipo',
            field=models.CharField(choices=[('PEI', 'PEI'), ('PD_UNI', 'PD Unidades Académicas'), ('PD_FUN', 'PD Funciones Institucionales')], default='PEI', max_length=10),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='planificacion.indicador'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='acumulativo',
            field=models.BooleanField(default=False, verbose_name='¿Es acumulativo?'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='calculo_invertido',
            field=models.BooleanField(default=False, verbose_name='¿Es cálculo invertido?'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='tipo',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico'), ('ESPECIFICO', 'Específico')], max_length=20, verbose_name='Tipo de objetivo'),
        ),
        migrations.CreateModel(
            name='ProgramaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anio_meta', models.IntegerField(blank=True, null=True)),
                ('linea_base_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_programa', to='planificacion.indicador')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_indicadores', to='planificacion.programa')),
            ],
            options={
                'unique_together': {('programa', 'indicador')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('programa_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='planificacion.programaindicador')),
            ],
            options={
                'ordering': ['anio'],
                'unique_together': {('programa_indicador', 'anio')},
            },
        ),
    ]
