# Generated by Django 6.0.2 on 2026-03-03 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivo',
            name='programa',
        ),
        migrations.AddField(
            model_name='objetivo',
            name='programas',
            field=models.ManyToManyField(blank=True, related_name='objetivos', to='planificacion.programa', verbose_name='Programas'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='tipo',
            field=models.CharField(choices=[('ESTRATEGICO', 'Estratégico'), ('ESPECIFICO', 'Específico')], max_length=20, verbose_name='Tipo de objetivo'),
        ),
    ]
