# Generated by Django 6.0.2 on 2026-02-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Programa / PD',
                'verbose_name_plural': 'Programas / PD',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'ordering': ['programa', 'nombre'], 'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='tipoindicador',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Indicador', 'verbose_name_plural': 'Tipos de Indicadores'},
        ),
        migrations.AddField(
            model_name='indicador',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='planificacion.programa'),
        ),
    ]
