# Generated by Django 6.0.2 on 2026-02-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_programa_alter_indicador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='planificacion.programa'),
        ),
    ]
