# Generated by Django 6.0.2 on 2026-05-05 13:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_remove_indicador_aplica_linea_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='MetaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['anio'],
            },
        ),
        migrations.AlterModelOptions(
            name='seguimientoindicador',
            options={'ordering': ['anio', 'semestre']},
        ),
        migrations.AlterUniqueTogether(
            name='seguimientoindicador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicador',
            name='frecuencia',
            field=models.CharField(choices=[('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='SEMESTRAL', max_length=10),
        ),
        migrations.AddField(
            model_name='indicador',
            name='umbral_aceptable',
            field=models.PositiveSmallIntegerField(default=70, help_text='Avance % desde el cual se considera amarillo (aceptable).'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='umbral_optimo',
            field=models.PositiveSmallIntegerField(default=90, help_text='Avance % desde el cual se considera verde (óptimo).'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programa',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programa',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('VIGENTE', 'Vigente'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10),
        ),
        migrations.AddField(
            model_name='programaindicador',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Peso relativo del indicador para el avance global ponderado.', max_digits=5),
        ),
        migrations.AddField(
            model_name='seguimientoindicador',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seguimientoindicador',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seguimientoindicador',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='planificacion/evidencias/'),
        ),
        migrations.AddField(
            model_name='seguimientoindicador',
            name='semestre',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primer semestre'), (2, 'Segundo semestre')], default=2),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tipoindicador',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='seguimientoindicador',
            unique_together={('programa_indicador', 'anio', 'semestre')},
        ),
        migrations.AddIndex(
            model_name='seguimientoindicador',
            index=models.Index(fields=['anio', 'semestre'], name='planificaci_anio_9aa460_idx'),
        ),
        migrations.AddIndex(
            model_name='seguimientoindicador',
            index=models.Index(fields=['programa_indicador', 'anio'], name='planificaci_program_8b295e_idx'),
        ),
        migrations.AddConstraint(
            model_name='programa',
            constraint=models.UniqueConstraint(condition=models.Q(('eliminado', False)), fields=('nombre', 'tipo'), name='programa_unico_nombre_tipo_activo'),
        ),
        migrations.AddField(
            model_name='cierreanual',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cierreanual',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='planificacion.programa'),
        ),
        migrations.AddField(
            model_name='metaindicador',
            name='programa_indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_anuales', to='planificacion.programaindicador'),
        ),
        migrations.AlterUniqueTogether(
            name='cierreanual',
            unique_together={('programa', 'anio')},
        ),
        migrations.AddIndex(
            model_name='metaindicador',
            index=models.Index(fields=['anio'], name='planificaci_anio_7b33b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metaindicador',
            unique_together={('programa_indicador', 'anio')},
        ),
    ]
