# Generated by Django 6.0.2 on 2026-03-04 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_remove_objetivo_programa_objetivo_programas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='plazo',
            field=models.CharField(choices=[('CORTO', 'Corto plazo'), ('MEDIANO', 'Mediano plazo'), ('LARGO', 'Largo plazo')], default='CORTO', max_length=10),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='planificacion.indicador', verbose_name='Indicador'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
