# Generated by Django 6.0.2 on 2026-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_cierreanual_metaindicador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaindicador',
            name='estado',
            field=models.CharField(choices=[('VALOR', 'Valor'), ('SM', 'Sin medición'), ('NA', 'No aplica')], default='VALOR', max_length=5),
        ),
        migrations.AddField(
            model_name='seguimientoindicador',
            name='estado',
            field=models.CharField(choices=[('VALOR', 'Valor'), ('SM', 'Sin medición'), ('NA', 'No aplica')], default='VALOR', max_length=5),
        ),
        migrations.AlterField(
            model_name='metaindicador',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='seguimientoindicador',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
