# Generated by Django 6.0.2 on 2026-02-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_alter_indicador_programa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={},
        ),
    ]
