# Generated by Django 6.0.2 on 2026-03-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_estrategia_plazo_alter_estrategia_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrategia',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estrategias', to='planificacion.indicador'),
        ),
    ]
