# Generated by Django 6.0.2 on 2026-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_metaindicador_estado_seguimientoindicador_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
    ]
