# Generated by Django 6.0.2 on 2026-03-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_estrategia_indicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='acumulativo',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='aplica_linea_base',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='calculo_invertido',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='indicador',
            name='meta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='objetivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='planificacion.objetivo'),
        ),
    ]
