# Generated by Django 6.0.2 on 2026-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_remove_indicador_acumulativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='acumulativo',
            field=models.BooleanField(default=False, verbose_name='¿Es acumulativo?'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='calculo_invertido',
            field=models.BooleanField(default=False, verbose_name='¿Es cálculo invertido?'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='formula',
            field=models.TextField(blank=True, help_text='Ej: (Cantidad lograda / Meta) * 100'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='linea_base',
            field=models.BooleanField(default=False, verbose_name='¿Aplica línea base?'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='unidad_medida',
            field=models.CharField(choices=[('CAR', 'Caracteres'), ('POR', 'Porcentual'), ('UNI', 'Unitario')], default='UNI', max_length=3),
        ),
    ]
