# Generated by Django 6.0.2 on 2026-03-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_indicador_acumulativo_indicador_calculo_invertido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivo',
            name='programas',
        ),
        migrations.AddField(
            model_name='programa',
            name='objetivos',
            field=models.ManyToManyField(blank=True, related_name='programas_asociados', to='planificacion.objetivo'),
        ),
    ]
