# Generated by Django 6.0.2 on 2026-03-04 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0007_remove_objetivo_programas_programa_objetivos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='meta',
        ),
        migrations.CreateModel(
            name='ProgramaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anio_meta', models.IntegerField(blank=True, null=True)),
                ('linea_base_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_programa', to='planificacion.indicador')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_indicadores', to='planificacion.programa')),
            ],
            options={
                'unique_together': {('programa', 'indicador')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('programa_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='planificacion.programaindicador')),
            ],
            options={
                'ordering': ['anio'],
                'unique_together': {('programa_indicador', 'anio')},
            },
        ),
    ]
