# Generated by Django 6.0.2 on 2026-07-29 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('modalidad', models.CharField(choices=[('ELEARNING', 'E-learning'), ('ELEARNING_ASINC', 'E-learning asincrónico'), ('BLEARNING', 'B-learning'), ('PRESENCIAL', 'Presencial')], default='ELEARNING', max_length=20)),
                ('n_participantes', models.PositiveIntegerField(default=0, verbose_name='N° participantes comprometidos')),
                ('horas', models.PositiveIntegerField(default=0)),
                ('tipo_relator', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('NO_DEFINIDO', 'No definido'), ('NO_APLICA', 'No aplica')], default='NO_DEFINIDO', max_length=20)),
                ('fecha_confirmacion_relator', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('proxima_fecha_critica', models.DateField(blank=True, null=True)),
                ('estado_ejecucion', models.CharField(choices=[('NO_PROGRAMADA', 'No programada'), ('PROGRAMADA', 'Programada'), ('EN_EJECUCION', 'En ejecución'), ('EJECUTADA', 'Ejecutada'), ('SUSPENDIDA', 'Suspendida')], db_index=True, default='NO_PROGRAMADA', max_length=20)),
                ('n_participantes_ejecucion', models.PositiveIntegerField(blank=True, null=True)),
                ('n_becados', models.PositiveIntegerField(blank=True, null=True)),
                ('n_aprobados', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_ofertado', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('costo_relatoria', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monto_adjudicado', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('n_factura', models.CharField(blank=True, max_length=50, verbose_name='N° factura')),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('monto_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / próximo paso')),
                ('responsable_seguimiento', models.CharField(blank=True, max_length=255)),
                ('actualizado_al', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['propuesta__codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('PUBLICA', 'Pública'), ('PRIVADA', 'Privada'), ('INTERNA', 'Interna UPLA'), ('PERSONA', 'Personas naturales')], default='PUBLICA', max_length=20)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'instituciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Relator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('tipo', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], default='EXTERNO', max_length=20)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'relator/a',
                'verbose_name_plural': 'relatores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='otec.institucion')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('PROPUESTA', 'Propuesta técnica'), ('RELATORIA', 'Relatoría'), ('PLATAFORMA', 'Plataforma'), ('COMUNICACION', 'Comunicación a participantes'), ('EJECUCION', 'Ejecución'), ('CIERRE', 'Cierre')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('critico', models.BooleanField(default=False, help_text='Si está pendiente, la actividad se marca con alerta crítica.')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ítem de checklist',
                'verbose_name_plural': 'plantilla de checklist',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('etapa', 'nombre'), name='otec_plantilla_item_unico')],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('SI', 'Sí'), ('NO', 'No'), ('NO_APLICA', 'No aplica')], default='PENDIENTE', max_length=20)),
                ('detalle', models.CharField(blank=True, help_text='Matiz del estado, p. ej. "En validación operativa".', max_length=255)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='otec.actividad')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='otec.plantillaitem')),
            ],
            options={
                'verbose_name': 'ítem de actividad',
                'verbose_name_plural': 'ítems de actividad',
                'ordering': ['plantilla__orden', 'plantilla__id'],
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('canal', models.CharField(choices=[('CONVENIO', 'Convenio / trato directo'), ('LICITACION', 'Licitación'), ('VENTA_DIRECTA', 'Venta directa / matrícula'), ('INTERNA', 'Gestión interna')], default='CONVENIO', max_length=20)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('estado_comercial', models.CharField(choices=[('EN_PREPARACION', 'En preparación'), ('ENVIADA', 'Enviada'), ('EN_REVISION', 'En revisión'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida'), ('DESISTIDA', 'Desistida')], db_index=True, default='EN_PREPARACION', max_length=20)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('anio', models.PositiveIntegerField(db_index=True)),
                ('estado_convenio', models.CharField(choices=[('NO_INICIADO', 'No iniciado'), ('EN_REVISION', 'En revisión'), ('EN_TRAMITE', 'En trámite'), ('FORMALIZADO', 'Formalizado')], default='NO_INICIADO', max_length=20)),
                ('observacion_convenio', models.CharField(blank=True, max_length=500)),
                ('estado_decretacion', models.CharField(choices=[('NO_INICIADO', 'No iniciado'), ('PENDIENTE_CONVENIO', 'Pendiente recepción convenio firmado'), ('PENDIENTE_INTERNA', 'Pendiente decretación interna'), ('LISTO', 'Listo')], default='NO_INICIADO', max_length=25)),
                ('memo_decretacion', models.CharField(blank=True, max_length=50)),
                ('fecha_memo', models.DateField(blank=True, null=True)),
                ('cr', models.CharField(blank=True, max_length=30, verbose_name='CR')),
                ('n_decreto', models.CharField(blank=True, max_length=50, verbose_name='N° decreto')),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas', to='otec.contacto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas', to='otec.institucion')),
            ],
            options={
                'verbose_name': 'propuesta',
                'verbose_name_plural': 'propuestas',
                'ordering': ['-anio', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='propuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='otec.propuesta'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='relator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='otec.relator'),
        ),
        migrations.AddConstraint(
            model_name='contacto',
            constraint=models.UniqueConstraint(fields=('institucion', 'nombre'), name='otec_contacto_unico_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='itemchecklist',
            constraint=models.UniqueConstraint(fields=('actividad', 'plantilla'), name='otec_item_unico_por_actividad'),
        ),
    ]
