# Generated by Django 6.0.2 on 2026-07-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuesta',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='actividad',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10),
        ),
    ]
