# Generated by Django 6.0.2 on 2026-07-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0002_remove_propuesta_prioridad_actividad_prioridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='SalaZoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sala Zoom',
                'verbose_name_plural': 'salas Zoom',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DiaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('E', 'Ejecución'), ('C', 'Cierre administrativo')], default='E', max_length=1)),
                ('horas_asincronicas', models.DecimalField(blank=True, decimal_places=1, help_text='Horas asincrónicas del día, si las hubo.', max_digits=4, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='otec.actividad')),
            ],
            options={
                'verbose_name': 'día de actividad',
                'verbose_name_plural': 'días de actividad (Gantt)',
                'ordering': ['fecha'],
                'constraints': [models.UniqueConstraint(fields=('actividad', 'fecha'), name='otec_dia_unico_por_actividad')],
            },
        ),
        migrations.CreateModel(
            name='ReservaZoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('etiqueta', models.CharField(help_text='Código tal como aparecía en la planilla, p. ej. "FORM (S.AP)".', max_length=120)),
                ('soporte', models.CharField(blank=True, help_text='Iniciales de quien da soporte, del paréntesis del código.', max_length=60)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('actividad', models.ForeignKey(blank=True, help_text='Vacío para usos que no corresponden a un curso del registro.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_zoom', to='otec.actividad')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='otec.salazoom')),
            ],
            options={
                'verbose_name': 'reserva de Zoom',
                'verbose_name_plural': 'reservas de Zoom',
                'ordering': ['fecha', 'hora_inicio', 'sala__orden'],
                'constraints': [models.UniqueConstraint(fields=('sala', 'fecha', 'hora_inicio'), name='otec_reserva_unica_por_bloque')],
            },
        ),
    ]
