# Generated by Django 6.0.2 on 2026-07-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0003_feriado_salazoom_diaactividad_reservazoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchecklist',
            name='editado_en_sistema',
            field=models.BooleanField(default=False, help_text='Marcado cuando alguien cambió el estado desde la aplicación. La importación del Excel respeta estos ítems salvo que se pida sobrescribirlos.'),
        ),
    ]
