# Generated by Django 6.0.2 on 2026-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0004_itemchecklist_editado_en_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'meta anual',
                'verbose_name_plural': 'metas anuales',
                'ordering': ['-anio'],
            },
        ),
    ]
