# Generated by Django 6.0.2 on 2026-07-29 19:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0005_metaanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoTransversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.CharField(max_length=300)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('criterio', models.CharField(blank=True, max_length=120)),
                ('incluir_en_flujo', models.BooleanField(default=True)),
                ('fuente_financiamiento', models.CharField(blank=True, max_length=120)),
                ('observacion', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'costo transversal',
                'verbose_name_plural': 'costos transversales',
                'ordering': ['fecha_pago', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SupuestosFinancieros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_corte', models.DateField(blank=True, help_text='Desde este mes se proyecta la caja; antes solo se registra lo ocurrido.', null=True)),
                ('valor_hora_relatoria', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pct_upla', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5, verbose_name='% de distribución UPLA')),
                ('pct_otec', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5, verbose_name='% de distribución OTEC')),
                ('pct_autoaprendizaje', models.DecimalField(decimal_places=4, default=Decimal('0.50'), help_text='Los cursos de autoaprendizaje se reparten mitad y mitad.', max_digits=5)),
                ('plazo_pago_costos_dias', models.PositiveIntegerField(default=40)),
                ('saldo_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'supuestos financieros',
                'verbose_name_plural': 'supuestos financieros',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='LineaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(max_length=300, verbose_name='Curso o servicio')),
                ('estado', models.CharField(choices=[('EJECUTADA', 'Ejecutada'), ('CONTRATADA', 'Contratada'), ('ADJUDICADA', 'Adjudicada'), ('EN_NEGOCIACION', 'En negociación'), ('PROYECTADA', 'Proyectada')], default='PROYECTADA', max_length=20)),
                ('certeza', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CONFIRMADO', 'Confirmado'), ('PROBABLE', 'Probable'), ('PROYECTADO', 'Proyectado')], db_index=True, default='PROYECTADO', max_length=15)),
                ('autoaprendizaje', models.BooleanField(default=False, help_text='Cambia el reparto a mitad y mitad en vez de 15/15.')),
                ('participantes', models.PositiveIntegerField(default=0)),
                ('horas', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('fecha_facturacion', models.DateField(blank=True, null=True)),
                ('fecha_pago_estimada', models.DateField(blank=True, null=True)),
                ('fecha_pago_efectiva', models.DateField(blank=True, null=True)),
                ('valor_ofertado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_contratado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('origen', models.CharField(blank=True, max_length=200)),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('actividad', models.ForeignKey(blank=True, help_text='Vacío en la cartera proyectada, que aún no es un curso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_financieras', to='otec.actividad')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_financieras', to='otec.institucion')),
            ],
            options={
                'verbose_name': 'línea financiera',
                'verbose_name_plural': 'líneas financieras',
                'ordering': ['fecha_pago_estimada', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='CostoDirecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatoria', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('materiales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('plataformas', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('certificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('traslados', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('alimentacion', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('arriendo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('otros', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_pago_estimada', models.DateField(blank=True, null=True)),
                ('fecha_pago_efectiva', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=40)),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('linea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo', to='otec.lineafinanciera')),
            ],
            options={
                'verbose_name': 'costo directo',
                'verbose_name_plural': 'costos directos',
            },
        ),
    ]
