# Generated by Django 6.0.2 on 2026-07-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0006_costotransversal_supuestosfinancieros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='origen',
            field=models.CharField(choices=[('IMPORTADO', 'Importado del Excel'), ('MANUAL', 'Creado en el sistema')], db_index=True, default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='propuesta',
            name='origen',
            field=models.CharField(choices=[('IMPORTADO', 'Importado del Excel'), ('MANUAL', 'Creado en el sistema')], db_index=True, default='MANUAL', max_length=10),
        ),
    ]
