# Generated by Django 6.0.2 on 2026-07-30 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0008_marcar_origen_importado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='responsables',
            field=models.ManyToManyField(blank=True, help_text='Quiénes del equipo OTEC llevan esta actividad.', related_name='actividades_otec', to=settings.AUTH_USER_MODEL, verbose_name='Responsables OTEC'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='responsable_seguimiento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Responsable según la planilla'),
        ),
    ]
