# Generated by Django 6.0.2 on 2026-08-03 13:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otec', '0010_grupos_otec'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, help_text='Solo si el curso dicta más de un grupo en paralelo, p. ej. «AP».', max_length=40)),
                ('dias', models.CharField(help_text='Días de la semana en que hay clase.', max_length=7)),
                ('hora_inicio', models.TimeField()),
                ('duracion_horas', models.DecimalField(decimal_places=1, default=Decimal('2.0'), max_digits=4, verbose_name='Duración de cada sesión (horas)')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='otec.actividad')),
                ('sala', models.ForeignKey(blank=True, help_text='Vacío si la clase no ocupa una sala Zoom.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='otec.salazoom')),
            ],
            options={
                'verbose_name': 'horario de clases',
                'verbose_name_plural': 'horarios de clases',
                'ordering': ['actividad', 'grupo', 'hora_inicio'],
            },
        ),
    ]
